deploy:
  stage: production
  image: dtzar/helm-kubectl
  before_script:
    - sed -i "s~<VERSION>~${CI_COMMIT_TAG}~g" .helm/Chart.yaml
  script:
    - helm upgrade covid-19-frontend .helm --namespace "${KUBE_NAMESPACE}" --install
  environment:
    name: production
  when: manual
  only:
    - tags
  except:
    - branches
